// Mock Customer360 service (real API: service A221).
//
// There is no real integration yet. getCustomer360() simulates one: it
// returns the same shape a real call would, after a short delay, so the
// ETB flow behaves as if it were talking to a live API.
//
// To connect the real service later, replace the body of getCustomer360()
// with the actual API call (plain fetch(), same pattern as
// src/services/customerSearchService.js) and keep the function signature
// and return shape the same - nothing that reads matchedCustomer.customer360
// elsewhere in the app needs to change.

const MOCK_REQUEST_DELAY_MS = 700;

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// Shivanjali's basic-inquiry fields are derived from her own flat
// MOCK_CUSTOMERS record (CustomerIdentityPage.jsx) - not invented separately.
// Fields with no equivalent anywhere else (customerId as a numeric CBS id,
// productDetails, the carat-wise summary) are fabricated for completeness,
// flagged here rather than silently made up.
const CUSTOMER_360_BY_MOBILE = {
  "8552051111": {
    customerResponse: {
      xfaceCustomerBasicInquiryDTO: {
        birthDate: "19961101",
        categoryType: "Resident Individual",
        combWithdrawBal: 42500,
        custType: "INDIVIDUAL",
        customerAddress: {
          city: "PUNE",
          country: "IN",
          line1: "D-303, FORTUNE ESTATE, HADAPSAR",
          line2: "NEAR MAGARPATTA ROAD",
          line3: "",
          state: "MAHARASHTRA",
          zip: "411028",
        },
        customerFullName: "SHIVANJALI GAIKWAD",
        customerId: 606501, // fabricated numeric CBS id - not given anywhere else
        emailAddress: "shivanjali.gaikwad@email.com",
        flgBlacklisted: "N",
        flgBlocked: "N",
        flgDeceased: "N",
        flgROIConcession: "N",
        flgRestrictedCust: "N",
        flgSuspended: "N",
        homeBranch: "YESB0000418",
        imageAvailable: false,
        kycStatus: "C",
        limitAmount: 0,
        mobileNumber: "8552051111",
        motherMaidenName: "",
        npaCategory: 1001,
        productDetails: [ // fabricated - shaped like the sample, not from a real call
          { productCode: "6745", productLimitUtilized: 0, totalAcctFinYear: 1, totalLiveAcctFinYear: 1 },
        ],
        rateROIConcession: 0,
        receivableAmt: 0,
        remainingRecvAmt: 0,
        sex: "Female",
        signatureAvailable: false,
      },
      xfaceCustomerMemoDTO: {},
    },
    xfaceCustomerAccountDetailsDTO: {
      xfaceAccountDetailsforCustomerDTO: [
        {
          accountId: "1018100428531", // fabricated - distinct from Deepak's real account numbers
          amtDisbursed: 250000,
          amtSanction: 250000,
          branchCode: "YESB0000418",
          branchName: "Pune - Hadapsar",
          currentBalance: 185000,
          currentStatusDescription: "ACCOUNT OPEN REGULAR",
          customerRelationship: "SOW",
          datAcctOpen: "20240612",
          datMaturity: "20260612",
          datSanction: "20240612",
          dateDPD: "19500101",
          dateLastPartialRelease: "18000101",
          dateLastRenewal: "18000101",
          dateLastTopup: "18000101",
          flgCPN: "N",
          flgMaturity: "N",
          lineNumber: "",
          maxDPD: 0,
          moduleCode: "L",
          npaAcctCategory: 1001,
          packetId: "P0418G0007",
          productCode: 6745,
          productName: "6745-Long Tenure High Value General Gold",
          productType: "Retail",
          ratInt: 9.49,
          rollOverNumber: 0,
          tenure: "24",
        },
      ],
      xfaceCasaAccountDTO: [
        {
          accountId: "102345678901",
          acctTitle: "SHIVANJALI GAIKWAD",
          branchCode: "YESB0000418",
          currentBalance: 42500,
          datAcctOpen: "20240612",
          moduleCode: "CA",
          netBalance: 42500,
          productCode: "2",
          productName: "Savings Account",
          relation: "SOW",
        },
      ],
      xfaceGoldCollateralsDTO: [],
      xfaceODDetailsDTO: [],
      xfaceODGoldCollateralsDTO: [],
    },
    // Fabricated for completeness (derived from her one gold loan above,
    // not from a real carat-wise call).
    xfaceExtGoldAllCaratWiseDTO: [
      { carat: "22", deduction: 2, grossWeight: 20, netWeight: 18, totalValue: 250000 },
    ],
    xfaceExtGoldCoinsCaratWiseDTO: [],
  },

  // Deepak Dev - the exact sample given for Customer360 (A221), verbatim,
  // with one deliberate change: mobile kept as 8787878787 (his own sample
  // value - it didn't collide with anything, so nothing needed changing).
  "8787878787": {
    customerResponse: {
      xfaceCustomerBasicInquiryDTO: {
        birthDate: "19810512",
        categoryType: "Resident Individual",
        combWithdrawBal: 1528437.93,
        custType: "INDIVIDUAL",
        customerAddress: {
          city: "ERNAKULAM",
          country: "IN",
          line1: "FORT KOCHI",
          line2: "ERNAKULAM",
          line3: "",
          state: "KERALA",
          zip: "686662",
        },
        customerFullName: "DEEPAK DEV",
        customerId: 606414,
        emailAddress: "deepak@gmail.com",
        flgBlacklisted: "N",
        flgBlocked: "N",
        flgDeceased: "N",
        flgROIConcession: "N",
        flgRestrictedCust: "N",
        flgSuspended: "N",
        homeBranch: "1015",
        imageAvailable: false,
        kycStatus: "C",
        limitAmount: 0,
        mobileNumber: "8787878787",
        motherMaidenName: "",
        npaCategory: 1001,
        productDetails: [
          { productCode: "6745", productLimitUtilized: 0, totalAcctFinYear: 1, totalLiveAcctFinYear: 0 },
          { productCode: "2", totalAcctFinYear: 0, totalLiveAcctFinYear: 2 },
          { productCode: "7710", productLimitUtilized: 1049850, totalAcctFinYear: 2, totalLiveAcctFinYear: 2 },
        ],
        rateROIConcession: 0,
        receivableAmt: 0,
        remainingRecvAmt: 0,
        sex: "Male",
        signatureAvailable: false,
      },
      xfaceCustomerMemoDTO: {},
    },
    xfaceCustomerAccountDetailsDTO: {
      xfaceAccountDetailsforCustomerDTO: [
        {
          accountId: "1015100000065",
          amtDisbursed: 500000,
          amtSanction: 500000,
          branchCode: "1015",
          branchName: "Mumbai-Corporate Office",
          currentBalance: 0,
          currentStatusDescription: "ACCOUNT OPENED TODAY",
          customerRelationship: "SOW",
          datAcctOpen: "20251004",
          datMaturity: "20290704",
          datSanction: "20251004",
          dateDPD: "19500101",
          dateLastPartialRelease: "18000101",
          dateLastRenewal: "18000101",
          dateLastTopup: "18000101",
          flgCPN: "N",
          flgMaturity: "N",
          lineNumber: "",
          maxDPD: 0,
          moduleCode: "L",
          npaAcctCategory: 1001,
          packetId: "",
          productCode: 6171,
          productName: "6171-MSME Small Business Loans-Unsecurd-",
          productType: "Retail",
          ratInt: 12,
          rollOverNumber: 0,
          tenure: "45",
        },
        {
          accountId: "1015100000020",
          amtDisbursed: 500000,
          amtSanction: 500000,
          branchCode: "1015",
          branchName: "Mumbai-Corporate Office",
          currentBalance: 0,
          currentStatusDescription: "ACCOUNT OPENED TODAY",
          customerRelationship: "GUA",
          datAcctOpen: "20251004",
          datMaturity: "20270404",
          datSanction: "20251004",
          dateDPD: "19500101",
          dateLastPartialRelease: "18000101",
          dateLastRenewal: "18000101",
          dateLastTopup: "18000101",
          flgCPN: "N",
          flgMaturity: "N",
          lineNumber: "",
          maxDPD: 0,
          moduleCode: "L",
          npaAcctCategory: 1001,
          packetId: "",
          productCode: 6441,
          productName: "6441-SHG TERM LOAN-REPO",
          productType: "Retail",
          ratInt: 6.5,
          rollOverNumber: 0,
          tenure: "18",
        },
        {
          accountId: "1015100000053",
          amtDisbursed: 200000,
          amtSanction: 200000,
          branchCode: "1015",
          branchName: "Mumbai-Corporate Office",
          currentBalance: 0,
          currentStatusDescription: "ACCOUNT OPENED TODAY",
          customerRelationship: "GUA",
          datAcctOpen: "20251004",
          datMaturity: "20270404",
          datSanction: "20251004",
          dateDPD: "19500101",
          dateLastPartialRelease: "18000101",
          dateLastRenewal: "18000101",
          dateLastTopup: "18000101",
          flgCPN: "N",
          flgMaturity: "N",
          lineNumber: "",
          maxDPD: 0,
          moduleCode: "L",
          npaAcctCategory: 1001,
          packetId: "",
          productCode: 6441,
          productName: "6441-SHG TERM LOAN-REPO",
          productType: "Retail",
          ratInt: 6.5,
          rollOverNumber: 0,
          tenure: "18",
        },
        {
          accountId: "1015100319295",
          amtDisbursed: 0,
          amtSanction: 1200000,
          branchCode: "1015",
          branchName: "Mumbai-Corporate Office",
          currentBalance: 0,
          currentStatusDescription: "ACCOUNT OPEN REGULAR",
          customerRelationship: "SOW",
          datAcctOpen: "20250131",
          datMaturity: "19500101",
          datSanction: "20250131",
          dateDPD: "20251130",
          dateLastPartialRelease: "18000101",
          dateLastRenewal: "18000101",
          dateLastTopup: "18000101",
          flgCPN: "N",
          flgMaturity: "N",
          lineNumber: "GOLDLINE41",
          maxDPD: 0,
          moduleCode: "L",
          npaAcctCategory: 1001,
          packetId: "",
          productCode: 6580,
          productName: "6580-Vehicle Loan-Commercial",
          productType: "Retail",
          ratInt: 9,
          rollOverNumber: 0,
          tenure: "60",
        },
        {
          accountId: "1015100318762",
          amtDisbursed: 1000000,
          amtSanction: 1000000,
          branchCode: "1015",
          branchName: "Mumbai-Corporate Office",
          currentBalance: 0,
          currentStatusDescription: "ACCOUNT CLOSED",
          customerRelationship: "SOW",
          datAcctOpen: "20250117",
          datMaturity: "20280717",
          datSanction: "20250117",
          dateDPD: "19500101",
          dateLastPartialRelease: "18000101",
          dateLastRenewal: "18000101",
          dateLastTopup: "18000101",
          flgCPN: "N",
          flgMaturity: "N",
          lineNumber: "GOLDLINE11",
          maxDPD: 0,
          moduleCode: "L",
          npaAcctCategory: 1001,
          packetId: "P1015L0001",
          productCode: 6745,
          productName: "6745-Long Tenure High Value General Gold",
          productType: "Retail",
          ratInt: 9.49,
          rollOverNumber: 0,
          tenure: "42",
        },
      ],
      xfaceCasaAccountDTO: [
        {
          accountId: "1015020006291",
          acctTitle: "DEEPAK DEV",
          branchCode: 1015,
          currentBalance: 0,
          datAcctOpen: "20250203",
          moduleCode: "CA",
          netBalance: 0,
          productCode: "7710",
          productName: "7710-OD GL Loan",
          relation: "SOW",
        },
      ],
      xfaceGoldCollateralsDTO: [],
      xfaceODDetailsDTO: [
        {
          accountId: "1015020005914",
          acctTitle: "DEEPAK DEV",
          branchCode: 1015,
          collateralDrawingPower: 0,
          currentBalance: 478587.93,
          datAcctOpen: "20250117",
          dateDPD: "20251130",
          drawingPower: 1049850,
          limitAmount: 1049850,
          limitExpiryDate: "20260117",
          limitId: 1,
          limitLine: "",
          limitStartDate: "20250117",
          maxDPD: 0,
          netBalance: 478587.93,
          npaAcctCategory: 1,
          productCode: "7710",
          productName: "7710-OD GL Loan",
          ratInt: 10.5,
          relation: "SOW",
        },
      ],
      xfaceODGoldCollateralsDTO: [],
    },
    xfaceExtGoldAllCaratWiseDTO: [
      { carat: "22", deduction: 38, grossWeight: 983, netWeight: 945, totalValue: 8365000 },
    ],
    xfaceExtGoldCoinsCaratWiseDTO: [],
  },
};

export async function getCustomer360(customerId, mobileNumber) {
  await delay(MOCK_REQUEST_DELAY_MS);

  // TODO(real API): replace this lookup with the actual A221 call, e.g.
  // POST /FCAPIService/CustomerInquiryService/processRequest
  // { args0: {...}, args1: { customerId } }
  const record = CUSTOMER_360_BY_MOBILE[mobileNumber];
  return record || null;
}
